In [1]:
import torch
import torch.nn as nn

In [4]:
position = torch.arange(0, 10).float().unsqueeze(0)
position

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [6]:
b = torch.tensor([[1,2],[3,4],[4,5]])
b.size(0)

3

In [43]:
a = torch.tensor([[[1., 20.,30., 0.],
         [9., 0., 40., 0.],
         [10., 0., 0., 0.],
         [5., 0., 0., 0.]],

        [[2., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [6., 0., 0., 0.]],

        [[3., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [7., 0., 0., 0.]],

        [[4., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [8., 0., 0., 0.]]])
a

tensor([[[ 1., 20., 30.,  0.],
         [ 9.,  0., 40.,  0.],
         [10.,  0.,  0.,  0.],
         [ 5.,  0.,  0.,  0.]],

        [[ 2.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 6.,  0.,  0.,  0.]],

        [[ 3.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 7.,  0.,  0.,  0.]],

        [[ 4.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 8.,  0.,  0.,  0.]]])

In [48]:
a[:,:,2]

tensor([[30., 40.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]])

In [12]:
m = nn.Conv1d(7, 512,3,padding=1)
input = torch.randn(32, 96, 7)
input = input.transpose(1, 2)
print(input.shape)
output = m(input)
output.shape


torch.Size([32, 7, 96])


torch.Size([32, 512, 96])

In [5]:
from pandas.tseries.frequencies import to_offset
from pandas.tseries import offsets

offset = to_offset("h")
offset

isinstance(offset, offsets.Hour)


True

In [2]:
import numpy as np 
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a[-2:]

array([8, 9])