In [1]:
import torch
import torch.nn as nn

In [4]:
position = torch.arange(0, 10).float().unsqueeze(0)
position

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [6]:
b = torch.tensor([[1,2],[3,4],[4,5]])
b.size(0)

3

In [43]:
a = torch.tensor([[[1., 20.,30., 0.],
         [9., 0., 40., 0.],
         [10., 0., 0., 0.],
         [5., 0., 0., 0.]],

        [[2., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [6., 0., 0., 0.]],

        [[3., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [7., 0., 0., 0.]],

        [[4., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [8., 0., 0., 0.]]])
a

tensor([[[ 1., 20., 30.,  0.],
         [ 9.,  0., 40.,  0.],
         [10.,  0.,  0.,  0.],
         [ 5.,  0.,  0.,  0.]],

        [[ 2.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 6.,  0.,  0.,  0.]],

        [[ 3.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 7.,  0.,  0.,  0.]],

        [[ 4.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 8.,  0.,  0.,  0.]]])

In [48]:
a[:,:,2]

tensor([[30., 40.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]])

In [12]:
m = nn.Conv1d(7, 512,3,padding=1)
input = torch.randn(32, 96, 7)
input = input.transpose(1, 2)
print(input.shape)
output = m(input)
output.shape


torch.Size([32, 7, 96])


torch.Size([32, 512, 96])

In [5]:
from pandas.tseries.frequencies import to_offset
from pandas.tseries import offsets

offset = to_offset("h")
offset

isinstance(offset, offsets.Hour)


True

In [2]:
import numpy as np 
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a[-2:]

array([8, 9])

# einsumのテスト


In [2]:
import torch
import torch.nn as nn

In [17]:
Key = torch.randn(32,96,30)
Query = torch.randn(32,96,30)
Value = torch.randn(32,96,30)

print("Key")
print(Key.shape)

Weight = torch.einsum("blp,bsq->bslq", Key, Query)

print("Weight")
print(Weight.shape)

Output = torch.einsum("blsp,bsq->blq", Weight, Value)

print("Output")
print(Output.shape)



Key
torch.Size([32, 96, 30])
Weight
torch.Size([32, 96, 96, 30])
Output
torch.Size([32, 96, 30])


In [44]:
x = torch.randn(32,96,7)

output = torch.tensor([])

print(output.shape)

for i in range(7):
    print(i)
    print(x[:,:,i].shape)
    if i == 0:
        output = x[:,:,i]
    else:
        # x[:,:,i] = torch.unsqueeze(x[:,:,i],dim=2)
        output = torch.stack([output,torch.unsqueeze(x[:,:,i],dim=2)],dim=2)

    print(output.shape)

# for feature in x[:,:,]:
#     print(feature.shape)

torch.Size([0])
0
torch.Size([32, 96])
torch.Size([32, 96])
1
torch.Size([32, 96])


RuntimeError: stack expects each tensor to be equal size, but got [32, 96] at entry 0 and [32, 96, 1] at entry 1

In [53]:
output = torch.tensor([])

print(output.shape)

for i in range(7):
    x_embed = torch.randn(32,96,10)
    if i==0:
        output = x_embed
    else:
        output = torch.cat([output,x_embed],dim=2)

print(output.shape)


torch.Size([0])
torch.Size([32, 96, 70])


In [68]:

x = torch.randn(32,96,7)

x = x.transpose(2,0)

output = torch.stack([ xi for xi in x])

output = output.transpose(2,0)

print(output.shape)

torch.Size([32, 96, 7])


In [70]:
x = torch.randn(32,96,7)


output = torch.stack([ xi for xi in x],dim=1)


print(output.shape)

torch.Size([96, 32, 7])


In [75]:
x = torch.randn(32,96)

x = x.unsqueeze(1)

print(x.size())

torch.Size([32, 1, 96])


In [1]:
import torch
import torch.nn as nn

In [4]:
# torch.Size([10, 1, 96]) + torch.Size([10, 32, 96]) 
x = torch.randn(10,1,96)
y = torch.randn(10,32,96)

print(x+y)

xy = x+y

print(xy.size())

tensor([[[-0.2826,  3.2298,  0.0380,  ..., -0.2450,  1.7257,  0.2071],
         [ 0.7381,  2.3802, -1.8642,  ...,  0.0525, -0.0237,  1.0749],
         [-1.7073,  1.3168, -2.2125,  ...,  0.9162,  0.4918,  0.1191],
         ...,
         [-0.7566,  3.5409, -0.5225,  ..., -0.2412,  0.5538,  0.9229],
         [ 0.4341,  1.1225, -2.6539,  ..., -0.5934,  2.0410,  0.1020],
         [ 1.3712,  2.7784, -1.4802,  ..., -0.9743,  1.0847, -0.4185]],

        [[ 0.4161, -0.6704, -0.7082,  ..., -3.3971,  1.6697,  0.5408],
         [ 3.1008, -1.5138, -1.6659,  ..., -1.6538,  0.3203,  2.1221],
         [ 1.4358, -1.5048, -0.8361,  ..., -2.0655,  2.1079,  0.6430],
         ...,
         [ 1.3879, -0.2303, -0.3796,  ..., -0.1197,  1.0635,  2.6048],
         [ 0.6353, -0.8038, -1.0490,  ..., -2.6092,  1.2127,  2.3631],
         [ 1.5164, -0.8600, -1.7247,  ..., -0.8739,  1.8617,  0.9046]],

        [[ 1.6951,  1.7699, -1.1079,  ..., -1.8755, -0.6096,  0.8794],
         [ 1.1377, -1.3112, -1.5209,  ..., -0